import AuthContext from '@/context/AuthContext';
import SWRConfigContext from '@/context/SWRConfigContext';
import { Open_Sans } from 'next/font/google';
import Navbar from '../components/Navbar';
import './globals.css';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={openSans.className}>
			<body className='w-full max-w-screen-xl mx-auto overflow-auto' suppressHydrationWarning>
				<AuthContext>
					<header className='z-10 sticky top-0 border-b bg-white'>
						<Navbar />
					</header>
					<main className='flex justify-center w-full min-h-full bg-neutral-50'>
						<SWRConfigContext>{children}</SWRConfigContext>
					</main>
				</AuthContext>
			</body>
		</html>
	);
}
